#VMTurbo Entity Types
 - entities
 - virtualapplications
 - applications
 - containers
 - virtualmachines
 - hosts
 - hostcomparison
 - datastores
 - diskarrays
 - storagecomparison
 - storagecontrollers
 - iomodules
 - switches
 - vpods
 - dpods
 - virtualdatacenters
 - datacenters